name: ble_project
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+2

environment:
#  sdk: '>=2.12.0 <3.0.0'
  sdk: '^3.9.2'

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.2
  # GetX
  get: 4.7.3
  # Net
  dio: ^5.9.0
  dio_cache_interceptor: ^4.0.5
  dio_cookie_manager: ^3.3.0
  json_annotation: ^4.0.1
  shared_preferences: ^2.4.17
  connectivity_plus: ^7.0.0
  # log
  logger: 1.1.0
  logger_easier: ^0.0.3+1
  # DB
  hive_ce: ^2.15.1
  hive_ce_flutter: ^2.3.3
  # localization
  easy_localization: ^3.0.8
  # tools
  animated_flip_widget: ^0.0.2
  zo_animated_border: ^1.0.4
  random_avatar: ^0.0.8
  flutter_svg: ^2.2.3
  fluttertoast: ^9.0.0
  flutter_smart_dialog: ^4.9.8+9
  flutter_slidable: ^4.0.3
  flutter_scroll_shadow: ^1.2.6
  action_slider: ^0.7.0
  carousel_slider: ^5.1.1
  cached_network_image: 3.4.1
  shimmer: 3.0.0
  add_to_cart_animation: ^2.0.4
  floating_draggable_widget: ^2.3.0
  vertical_card_pager: ^1.6.3
  flutter_rating_bar: 4.0.1
  flutter_form_builder: ^10.2.0
  easy_refresh: ^3.4.0
  grouped_list: ^4.1.0
  # chart
  save_points_chart: ^1.3.1
  # dlna
  dlna_dart: '>=0.0.8'
  # Player
  fijkplayer_plus: ^0.0.1
  media_kit: ^1.2.2 # Primary package.
  media_kit_video: ^2.0.0 # For video rendering.
  media_kit_libs_video: ^1.0.7 # Native video dependencies.
  # wakelock: ^0.6.2
  wakelock_plus: ^1.4.0
  # FPS
  keframe: 2.0.2
  statsfl: ^2.2.0+1
  # autosize
  flutter_autosize_screen_pro: ^0.0.2
  # Html
  flutter_html: ^3.0.0
  # Splash
  flutter_native_splash: ^2.4.7
  # lifecycle
  lifecycle: ^0.10.0
  flutter_lifecycle_detector: ^0.0.8

dependency_overrides:
  sqflite_android: 2.4.1 # 此处替换为你想要的版本号

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  hive_ce_generator: ^1.10.1
#  build_runner: ^1.12.2
  build_runner: ^2.10.4
  json_serializable: ^6.11.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - res/graphic/
  - assets/
  - assets/translations/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
  - family: Muli
    fonts:
    - asset: res/fonts/Muli-Bold.ttf
    - asset: res/fonts/Muli-SemiBold.ttf
    - asset: res/fonts/Muli-Regular.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_native_splash:
  color: "#ffffff"
  image: assets/logo.png
  color_dark: "#002832"
  image_dark: assets/logo_dark.png
  android_12:
    image: assets/android12splash.png
    icon_background_color: "#eeeeee"