// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:ble_project/ui/detail/movie_detail_controller/model/film_box_info.dart';
import 'package:ble_project/ui/user/personal/model/movie_info.dart';
import 'package:ble_project/ui/user/personal/model/person_info.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(FilmBoxInfoAdapter());
    registerAdapter(MovieInfoAdapter());
    registerAdapter(PersonInfoAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(FilmBoxInfoAdapter());
    registerAdapter(MovieInfoAdapter());
    registerAdapter(PersonInfoAdapter());
  }
}
